on:
  push:
    tags:
    - '*'

name: Create Release (MacOS)

jobs:
  build:
    name: Create Release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      # Runs a single command using the runners shell

      - name: yarn install
        run: yarn install

      - name: build main
        run: yarn build-main

      - name: build rendere
        run: yarn build-renderer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          ENV: production
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          DEBUG_PROD: false
          DISABLE_MIXPANEL: 1
          SENTRY_DRY_RUN: true
          SENTRY_API_KEY: ${{ secrets.SENTRY_API_KEY }}
          SENTRY_TOKEN: ${{ secrets.SENTRY_API_KEY }}
          SENTRY_LOG_LEVEL: info

      # Runs a set of commands using the runners shell
      - name: yarn dist
        run: yarn dist
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "release/Chronos*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
