on:
  push:
    branches: [ master ]

name: Create Release (Windows)

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      # Runs a single command using the runners shell
      - name: yarn install
        run: yarn install

      # Runs a set of commands using the runners shell
      - name: yarn disk
        run: yarn dist
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false