on:
  push:
    branches: [ release ]

name: Create Release (Windows)

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      # Runs a single command using the runners shell
      - name: dependencies
        run: sudo apt-get install -y libssl-dev libxcursor-dev libxcomposite-dev libxdamage-dev libxrandr-dev libfontconfig1-dev libxss-dev

      - name: yarn install
        run: yarn install

      - name: build main
        run: yarn build-main

      - name: build rendere
        run: yarn build-renderer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          ENV: production
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          DEBUG_PROD: false
          DISABLE_MIXPANEL: 1
          SENTRY_DRY_RUN: true
          SENTRY_API_KEY: ${{ secrets.SENTRY_API_KEY }}
          SENTRY_TOKEN: ${{ secrets.SENTRY_API_KEY }}
          SENTRY_LOG_LEVEL: info

      # Runs a set of commands using the runners shell
      - name: yarn dist
        run: yarn dist
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          ENV: production
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          DEBUG_PROD: false
          DISABLE_MIXPANEL: 1
          SENTRY_DRY_RUN: true
          SENTRY_API_KEY: ${{ secrets.SENTRY_API_KEY }}
          SENTRY_TOKEN: ${{ secrets.SENTRY_API_KEY }}
          SENTRY_LOG_LEVEL: info
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: meeDamian/github-release@0.1
        with:
          files: 'release/'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}